### PR TITLE
Bumped compileSdkVersion, dependencies

### PR DESCRIPTION
**Pull request by Quadrified**
Android side changes only. Since, I need to use this repository to convert Image to PDF, I updated compileSdkVersion to 29, and also replaced the 'compile' keyword with 'implementation' in the dependencies.

### CODE REVIEW

**Comment by thekevinbrown** [comment]
Hi there, thanks for the PR.

Could you tell me a bit about why you needed to make these changes? You should be able to convert images to PDF with this code without these changes, unless I'm missing something...?

**Comment by Quadrified** [comment]
Hey, 
Since the React native version that I am using for the project is now > 0.60, and also the Android Build version that we are using is > 3.0; it requires us to use the newer build tools version, and also the keyword compile is replaced with implementation; and those are the two errors I get when I am building the project in the Andorid studio. 
I bumped the buildToolsVersion and replaced the compile keyword, and that solved my build issues. But the other colleagues who are installing the library and running the project, they're facing the same errors since the library is not yet updated.
Hope you merge the PR. We'll really appreciate that.
Thanks.

**Comment by Quadrified** [comment]
> Hi there, thanks for the PR.
> 
> Could you tell me a bit about why you needed to make these changes? You should be able to convert images to PDF with this code without these changes, unless I'm missing something...?

Hey,
Since the React native version that I am using for the project is now > 0.60, and also the Android Build version that we are using is > 3.0; it requires us to use the newer build tools version, and also the keyword compile is replaced with implementation; and those are the two errors I get when I am building the project in the Andorid studio.
I bumped the buildToolsVersion and replaced the compile keyword, and that solved my build issues. But the other colleagues who are installing the library and running the project, they're facing the same errors since the library is not yet updated.
Hope you merge the PR. We'll really appreciate that.
Thanks.

**Comment by thekevinbrown** [comment]
Got it, thanks!

**Comment by Quadrified** [comment]
> Got it, thanks!

Thanks for merging :)
I saw your commit that bumped the version from 0.2.1 to 1.0.0
 But while installing the package through yarn or npm gives the same old 0.2.1 package.

Can you help me out? Or am I doing something wrong while installing the package to get the latest version?

**Comment by thekevinbrown** [comment]
I don’t yet have publish permissions on NPM for this library. I’ve asked to be added, so either @Hopding will publish this or he’ll add me so I can.

**Comment by Quadrified** [comment]
> I don’t yet have publish permissions on NPM for this library. I’ve asked to be added, so either @Hopding will publish this or he’ll add me so I can.

Thanks. 
@Hopding can you please publish the changes ASAP!

**Pull request merged**
