### PR TITLE
Fix pods

### PR DESCRIPTION
**Pull request by retyui**

### CODE REVIEW

**Comment by thekevinbrown** [comment]
Hey there,

Thanks for the PR! What exactly was broken with the pods, and what does this fix? Is it compatible with all RN versions or just some?

**Comment by retyui** [comment]
After auto-linking doesn't work correctly on iOS RN@0.60.x

via: https://github.com/Hopding/react-native-pdf-lib/issues/57#issuecomment-597171290

**Comment by thekevinbrown** [comment]
Ok, will need to do a breaking change release for it in that case, will queue that up.

**Comment by retyui** [comment]
another polite reminder @thekevinbrown

**Pull request closed without merging**
